### ISSUE TITLE
[Feature Request] G++ cross compiler

### ISSUE THREAD

**Issue by Pix13** [lantw44/copr-rpm-spec#4]
Would it be possible to build the gcc-g++ cross compiler as well ? i'd like to use your ebuilds as a cross-distcc toolchain for a small armv7 rpm builder

**Comment by lantw44** [comment]
G++ is included in the gcc package. You can check it by running gcc with `-v` argument. It should show:
```
Configured with: ../gcc-7.3.0/configure ... --enable-languages=c,c++,fortran,objc,obj-c++,ada
```

**Comment by Pix13** [comment]
Oh! And here i was only searchin for g++ bin :) Thank you!
