### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by amivaleo** [lantw44/copr-rpm-spec#5]
Hi!

I'd like to reduce epiphany tabs on Fedora 30.

Can you please provide a step-by-step installation guide with clear instructions?

Thank you!

**Comment by lantw44** [comment]
If you just want to install the package, use the repository on Copr: https://copr.fedorainfracloud.org/coprs/lantw44/epiphany-reduce-tab-width/.

If you want to build it from sources, download the corresponding version of source RPM from Fedora and build it with the spec file  and the patch file included in this repository.

**Comment by amivaleo** [comment]
> If you just want to install the package, use the repository on Copr: https://copr.fedorainfracloud.org/coprs/lantw44/epiphany-reduce-tab-width/.

I don't know what to do with this link: https://copr.fedorainfracloud.org/coprs/lantw44/epiphany-reduce-tab-width/repo/fedora-30/lantw44-epiphany-reduce-tab-width-fedora-30.repo

**Comment by amivaleo** [comment]
Thank you. I solved this.
