### ISSUE TITLE
tcc: error: mprotect failed: did you mean to configure --with-selinux?

### ISSUE THREAD

**Issue by cz172638** [lantw44/copr-rpm-spec#7]
trying example from 2.1 section of [tcc docs](https://bellard.org/tcc/tcc-doc.html#Option-summary):
echo '#include <stdio.h> main(){printf("Hello World\n");return 0;}' | tcc -run -
tcc: error: mprotect failed: did you mean to configure --with-selinux?

**Comment by lantw44** [comment]
Fixed in version 0.9.27-7.

**Comment by cz172638** [comment]
yes, thanks, do you plan to get tcc to fedora?

**Comment by lantw44** [comment]
No, but I plan to update tcc to the latest git snapshot. The current version can't link executables since Fedora 29.
